### ISSUE TITLE
Vuetify dialog popup draw issue

### ISSUE THREAD

**Issue by parisnakitakejser** [neighborhood999/vue-signature-pad#99] opened 2019-02-03 19:27 UTC
When you use it in Vuetify and use dialog the draw function stop working, its working out of the box if you just put it in your component but when you use dialog its broken.

**Comment by TheWaffleDimension** [comment] 2019-02-09 21:07
Possible duplicate of #81?

**Comment by pynner** [comment] 2019-04-10 14:00
Yeah this is a still a problem. My fix is:

    async openDialogSignature() {
      this.dialog_signature.open = true;
      await Vue.nextTick();
      this.$refs.signaturePad.resizeCanvas();
    },

**Closed** 2019-05-30 15:05 UTC
